/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EpoukazRouteImport } from './routes/epoukaz'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as NavstevaRouteImport } from './routes/navsteva'
import { Route as RemesloRouteImport } from './routes/remeslo'
import { Route as SoukromiRouteImport } from './routes/soukromi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EpoukazRoute = EpoukazRouteImport.update({
  id: '/epoukaz',
  path: '/epoukaz',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const NavstevaRoute = NavstevaRouteImport.update({
  id: '/navsteva',
  path: '/navsteva',
  getParentRoute: () => rootRouteImport,
} as any)
const RemesloRoute = RemesloRouteImport.update({
  id: '/remeslo',
  path: '/remeslo',
  getParentRoute: () => rootRouteImport,
} as any)
const SoukromiRoute = SoukromiRouteImport.update({
  id: '/soukromi',
  path: '/soukromi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/epoukaz': typeof EpoukazRoute
  '/kontakt': typeof KontaktRoute
  '/navsteva': typeof NavstevaRoute
  '/remeslo': typeof RemesloRoute
  '/soukromi': typeof SoukromiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/epoukaz': typeof EpoukazRoute
  '/kontakt': typeof KontaktRoute
  '/navsteva': typeof NavstevaRoute
  '/remeslo': typeof RemesloRoute
  '/soukromi': typeof SoukromiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/epoukaz': typeof EpoukazRoute
  '/kontakt': typeof KontaktRoute
  '/navsteva': typeof NavstevaRoute
  '/remeslo': typeof RemesloRoute
  '/soukromi': typeof SoukromiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/epoukaz' | '/kontakt' | '/navsteva' | '/remeslo' | '/soukromi'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/epoukaz' | '/kontakt' | '/navsteva' | '/remeslo' | '/soukromi'
  id:
    | '__root__'
    | '/'
    | '/epoukaz'
    | '/kontakt'
    | '/navsteva'
    | '/remeslo'
    | '/soukromi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EpoukazRoute: typeof EpoukazRoute
  KontaktRoute: typeof KontaktRoute
  NavstevaRoute: typeof NavstevaRoute
  RemesloRoute: typeof RemesloRoute
  SoukromiRoute: typeof SoukromiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epoukaz': {
      id: '/epoukaz'
      path: '/epoukaz'
      fullPath: '/epoukaz'
      preLoaderRoute: typeof EpoukazRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navsteva': {
      id: '/navsteva'
      path: '/navsteva'
      fullPath: '/navsteva'
      preLoaderRoute: typeof NavstevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remeslo': {
      id: '/remeslo'
      path: '/remeslo'
      fullPath: '/remeslo'
      preLoaderRoute: typeof RemesloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soukromi': {
      id: '/soukromi'
      path: '/soukromi'
      fullPath: '/soukromi'
      preLoaderRoute: typeof SoukromiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EpoukazRoute: EpoukazRoute,
  KontaktRoute: KontaktRoute,
  NavstevaRoute: NavstevaRoute,
  RemesloRoute: RemesloRoute,
  SoukromiRoute: SoukromiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
